$:
    vscode:
        - docker:
            image: docker.cnb.cool/xmzzuzhi/cnb-docker/node:0.0.1
          imports:
            - https://cnb.cool/XMZZUZHI/key/-/blob/main/cnb.yml
          runner:
            cpus: 32
          services:
            - vscode
            - docker
          stages:
              - name: 授予install_gpg_keys.sh权限
                script:
                    - chmod +x /workspace/install_gpg_keys.sh
              - name: 安装iflow
                script:
                    - npm i -g @iflow-ai/iflow-cli@latest
                    - echo "iflow安装完成"
              - name: 安装sudo更新APT源
                script:
                    - sudo apt-get update
                    - sudo apt-get install -y lsof net-tools
                    - echo "依赖完成"
              - name: 安装Git LFS
                script:
                    - sudo apt-get install -y git-lfs
                    - git lfs install
                    - echo "Git LFS安装完成"
              - name: 下载并替换settings.json
                script:
                    - mkdir -p /root/.iflow
                    - curl -o /root/.iflow/settings.json https://astrbot.mizhoubaobei.top/1.json
                    - echo "已下载并替换 /root/.iflow/settings.json"
              - name: 安装iflow智能体
                script:
                    - chmod +x /workspace/install_agents.sh
                    - /workspace/install_agents.sh
    push:
        - services:
            - docker
          imports:
            - https://cnb.cool/XMZZUZHI/key/-/blob/main/Github.yml
          stages:
            - name: 同步到GitHub
              image: tencentcom/git-sync 
              settings:
                target_url: https://github.com/xiaomizhoubaobei/z-image-web.git
                auth_type: https
                username: ${GIT_USERNAME} 
                password: ${GIT_ACCESS_TOKEN}
                branch: main
                git_user: ${GIT_USERNAME}
                git_email: ${GIT_EMAIL}